spring.application.name=aditya-solar-management-api
spring.profiles.default=dev
server.port=${SERVER_PORT:8080}
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
